sudo: false
language: node_js
node_js:
- 6
cache:
  directories:
  - node_modules
before_install:
  - npm install grunt-cli typings -g
script:
  - grunt test
deploy:
  provider: script
  script: "grunt cd-latest"
  skip_cleanup: true
  on:
    branch: master
